Added GitHub CI/CD workflows
kaizentm/cloud-native-ops pull request #1
Opened 2021-02-18 20:59 UTC by bjcmit

Added the following GitHub workflows:

- CI and CD-Dev
- Dev-Test and CD-Stage
- Stage-Test

2021-02-19 20:37 UTC, eedorenko requested changes
Great job!
A few comments to iron out.

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +      CLUSTER_ENTRY_URL: http://13.88.133.114
Should be in environment secret

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +      DEMO_APP_URL: /azvote-dev
Should be in environment secret

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cicd.yml
> +      PLATFORM: "GitHub"
These env values should be in environment secrets

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +        PLATFORM: "GitHub"
These env values should be in environment secrets

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +        uses: dawidd6/action-download-artifact@v2
we need to download artifacts corresponding to a specific commit id rather than latest. This commit id should arrive from the connector as a parameter of  repository_dispatch event.

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +  PAT: ${{ secrets.PAT }}
Move these values to secrets

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cicd.yml
> +  PAT: ${{ secrets.PAT }}
Move to secrets

2021-02-19 20:37 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +    types: [dev-sync-success]
How does the connector know what event type to send? dev-sync-success? stage-sync-success?

2021-02-19 21:48 UTC, bjcmit commented on .github/workflows/az-vote-cicd.yml
> +        for file in ${{ github.workspace }}/${{ env.IMAGE_ARTIFACT_PATH }}/*; do echo "##vso[task.setvariable variable=${file##*/}]$(cat $file)"; done
So, it should be: 
`for file in ${{ github.workspace }}/${{ env.IMAGE_ARTIFACT_PATH }}/*; do echo "::set-env name=${file##*/}::$(cat $file)"; done`

2021-02-22 18:56 UTC, bjcmit commented on utils/create-pr.sh
> +    repo_url="https://bjcmit:$TOKEN@$repo_url"
Thought it needed the corresponding user name, but it does not.

2021-02-22 19:00 UTC, bjcmit commented on .github/workflows/az-vote-cd.yml
> +    types: [dev-sync-success]
The branch name will let the connector know what event type to send.

2021-02-22 22:22 UTC, eedorenko approved these changes

2021-02-22 22:22 UTC, eedorenko commented on .github/workflows/az-vote-cd.yml
> +        uses: dawidd6/action-download-artifact@v2
github.event.sha will give you the latest commit on the default branch. This is not what you want here. You want commit id of the merged PR (to which connector reports the commit status). So this commit id should be added to the [events payload](https://github.com/kaizentm/kubemlops/blob/dc23d7661488d70cdb871f6e47ccfd61b572e5b4/code/pipeline.py#L20). You can fix/test it when you will massage the connector to get the whole flow working.

2021-02-22 22:51 UTC, merged