Branching strategy
kaizentm/cloud-native-ops pull request #12
Opened 2021-06-11 16:11 UTC by eedorenko

Branching strategy in GitOps environment

2021-06-12 00:30 UTC, dtzar requested changes

2021-06-12 00:30 UTC, dtzar commented on docs/versions-branching-strategy.md
> +|2. A manifest repo per version, a branch per environment|Repos: Current, 1.0.x, 1.1.x <br/> Branches: Dev, QA, Prod |Clean separation/visibility| - Overwhelming number of repos <br/> - Pain to creat
It feels like we should almost explicitly tell people the options which likely are not a good one to use and/or suggest the best / most common 1 or 2. I'm not convinced 1. is the best option all-up. As you mentioned there is the combo possibility, tag/releases, etc.  

Are there customers or public references doing a specific config which scales?

2021-06-12 00:30 UTC, dtzar commented on docs/versions-branching-strategy.md
> +As it was mentioned, the manifests for different microservices are separated by folders. So, for example, the front-end and back-end CD pipelines for KubeKaizen 1.0.x will deliver their manifests to
What if KubeKaizen wants to maintain different release versions per microservice? This is a common best practice because you shouldn't have to release microservices together.

2021-06-12 00:30 UTC, dtzar commented on docs/versions-branching-strategy.md
> +The CI/CD pipelines setup for different versions depends pretty much on the orchestrator. What is common, is that CD pipelines for different versions should operate with different configuration sets
Again, what about automation of releases (which is essentially just tag of a commit on a branch)?
https://cli.github.com/manual/gh_release_create

2021-06-12 00:30 UTC, dtzar commented on docs/versions-branching-strategy.md
> +|Branch|Description|Lifespan|Merging|
This looks like you're using our de-facto example [trunk-based release flow](https://aka.ms/releaseflow) 👍.  We should call it out.

2021-06-12 00:33 UTC, tcare commented
Using '/' as a branch separator has tool support to help abstract away branching structures, albeit in an unstandardized way. It would be interesting to see if leveraging that could reduce some clutter.

2021-06-12 00:34 UTC, dtzar commented on docs/versions-branching-strategy.md
> +|Branch|Description|Lifespan|Merging|
This is [the newer link ](https://docs.microsoft.com/devops/develop/how-microsoft-develops-devops) it seems which is maintained.

2021-06-15 01:03 UTC, eedorenko commented on docs/versions-branching-strategy.md
> +|1. Single manifest repo, different sets of branches (a branch per environment-version)|Repo: Manifests <br/> Branches:  (Dev, QA, Prod), (Dev_1.0.x, QA_1.0.x, Prod_1.0.x), (Dev_1.1.x-, QA_1.1.x, Pro
Had the tagging column in source branches table originally, then removed ... added back with some clarifications. 
Added tags to the manifest repo too.

2021-06-15 01:05 UTC, eedorenko commented on docs/versions-branching-strategy.md
> +The CI/CD pipelines setup for different versions depends pretty much on the orchestrator. What is common, is that CD pipelines for different versions should operate with different configuration sets
Added chapter on release automation.

2021-06-15 01:06 UTC, eedorenko commented on docs/versions-branching-strategy.md
> +|Branch|Description|Lifespan|Merging|
Referenced Microsoft resources

2021-06-15 01:08 UTC, eedorenko commented on docs/versions-branching-strategy.md
> +|2. A manifest repo per version, a branch per environment|Repos: Current, 1.0.x, 1.1.x <br/> Branches: Dev, QA, Prod |Clean separation/visibility| - Overwhelming number of repos <br/> - Pain to creat
Added recommendation of #4

2021-06-15 01:09 UTC, eedorenko commented on docs/versions-branching-strategy.md
> +As it was mentioned, the manifests for different microservices are separated by folders. So, for example, the front-end and back-end CD pipelines for KubeKaizen 1.0.x will deliver their manifests to
Added text on that mater. Perhaps a supporting sample for this article should demonstrate one of the models.

2021-06-15 15:54 UTC, merged